# Tensorflow Syntax

In [1]:
import tensorflow as tf
import numpy as np
import pprint

tf.set_random_seed(777)

pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

### Simple Array

In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])

pp.pprint(t)
print("Rank :", t.ndim)
print("Shape :", t.shape)
print(t[0], t[1], t[2])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

array([0., 1., 2., 3., 4., 5., 6.])
Rank : 1
Shape : (7,)
0.0 1.0 2.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


### 2D Array

In [3]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])

pp.pprint(t)
print("Rank :", t.ndim)
print("Shape :", t.shape)

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])
Rank : 2
Shape : (4, 3)


### Shape, Rank, Axis

In [4]:
t = tf.constant([1, 2, 3, 4])

tf.shape(t).eval()

array([4])

In [5]:
t = tf.constant([[1, 2],
                 [3, 4]])

tf.shape(t).eval()

array([2, 2])

In [6]:
t= tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])

tf.shape(t).eval()

array([1, 2, 3, 4])

### Matmul VS Multiply

In [7]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],
                       [2.]])

In [8]:
tf.matmul(matrix1, matrix2).eval()

array([[12.]], dtype=float32)

In [9]:
(matrix1 * matrix2).eval()  # Broadcasting

array([[6., 6.],
       [6., 6.]], dtype=float32)

### Broadcasting

In [10]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.], [2.]])

(matrix1 + matrix2).eval()

array([[5., 5.],
       [5., 5.]], dtype=float32)

In [11]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])

(matrix1 + matrix2).eval()

array([[5., 5.]], dtype=float32)

### Random Values

In [12]:
tf.random_normal([3]).eval()

array([ 1.211047  ,  0.5397847 , -0.41038424], dtype=float32)

In [13]:
tf.random_uniform([2]).eval()

array([0.77554226, 0.9517144 ], dtype=float32)

In [14]:
tf.random_normal([2, 3]).eval()

array([[ 1.7077001 ,  0.34572503, -1.1328691 ],
       [ 1.2910684 ,  2.86688   ,  0.4344085 ]], dtype=float32)

### Mean && Sum

In [15]:
tf.reduce_mean([1, 2], axis=0).eval()  # Result is an integer

1

In [16]:
x = [[1., 2.],
     [3., 4.]]

In [17]:
tf.reduce_mean(x).eval()

2.5

In [18]:
tf.reduce_mean(x, axis=0).eval()

array([2., 3.], dtype=float32)

In [19]:
tf.reduce_mean(x, axis=1).eval()

array([1.5, 3.5], dtype=float32)

In [20]:
tf.reduce_mean(x, axis=-1).eval()  # 가장 안 쪽 값

array([1.5, 3.5], dtype=float32)

In [21]:
tf.reduce_sum(x).eval()

10.0

In [22]:
tf.reduce_sum(x, axis=0).eval()

array([4., 6.], dtype=float32)

In [23]:
tf.reduce_sum(x, axis=1).eval()

array([3., 7.], dtype=float32)

In [24]:
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval()

5.0

### Argmax with axis

In [25]:
x = [[0., 1., 2.],
     [2., 1., 0.]]

In [26]:
tf.argmax(x).eval()

array([1, 0, 0], dtype=int64)

In [27]:
tf.argmax(x, axis=0).eval()

array([1, 0, 0], dtype=int64)

In [28]:
tf.argmax(x, axis=1).eval()

array([2, 0], dtype=int64)

### .reshape, .squeeze, .expand_dims

In [29]:
t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              
              [[6, 7, 8], 
               [9, 10, 11]]])

t.shape

(2, 2, 3)

In [30]:
tf.reshape(t, shape=[-1, 3]).eval()  # 보통 맨 안쪽의 원소 갯수는 변하지 않으므로 맞춰준다.

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [31]:
tf.reshape(t, shape=[-1, 1, 3]).eval()

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [32]:
tf.squeeze([[0], [1], [2]]).eval()

array([0, 1, 2])

In [33]:
tf.expand_dims([0, 1, 2], 1).eval()  # 뒤의 인자는 늘릴 차원의 갯수.

array([[0],
       [1],
       [2]])

### One-Hot Encoding

In [34]:
tf.one_hot([[0], [1], [2], [0]], depth=3).eval()  # 무조건 한 차원 더 들어난다.

array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[1., 0., 0.]]], dtype=float32)

In [35]:
# 그래서 reshape 을 통해 원하는 형태로 다시 맞춰줘야 한다.
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
tf.reshape(t, shape=[-1, 3]).eval()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

In [36]:
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval()  # 무조건 내림

array([1, 2, 3, 4])

In [37]:
tf.cast([True, False, 1 == 1, 1 == 0], tf.int32).eval()  # 형변환 자유로움

array([1, 0, 1, 0])

### Stack

In [38]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

In [39]:
tf.stack([x, y, z]).eval()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [40]:
tf.stack([x, y, z], axis=0).eval()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [41]:
tf.stack([x, y, z], axis=1).eval()

array([[1, 2, 3],
       [4, 5, 6]])

### .ones_like && .zeros_like

In [42]:
x = [[0, 1, 2],
     [2, 1, 0]]

In [43]:
tf.ones_like(x).eval()

array([[1, 1, 1],
       [1, 1, 1]])

In [44]:
tf.zeros_like(x).eval()

array([[0, 0, 0],
       [0, 0, 0]])

### Zip

In [45]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [46]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9


### Transpose

In [47]:
t = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])

pp.pprint(t.shape)
pp.pprint(t)

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [48]:
t_trans1 = tf.transpose(t, [1, 0, 2])

pp.pprint(sess.run(t_trans1).shape)
pp.pprint(sess.run(t_trans1))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 6,  7,  8]],

       [[ 3,  4,  5],
        [ 9, 10, 11]]])


In [49]:
t_trans2 = tf.transpose(t_trans1, [1, 0, 2])

pp.pprint(sess.run(t_trans2).shape)
pp.pprint(sess.run(t_trans2))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [50]:
t_trans3 = tf.transpose(t_trans2, [1, 2, 0])

pp.pprint(sess.run(t_trans3).shape)
pp.pprint(sess.run(t_trans3))

(2, 3, 2)
array([[[ 0,  6],
        [ 1,  7],
        [ 2,  8]],

       [[ 3,  9],
        [ 4, 10],
        [ 5, 11]]])


In [51]:
t_trans4 = tf.transpose(t_trans3, [2, 0, 1])

pp.pprint(sess.run(t_trans4).shape)
pp.pprint(sess.run(t_trans4))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])
